//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Truss2D.Shell {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Truss2D.Shell.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a force on a joint. 
        ///    Syntax: &apos;exert a 5 3&apos;.  This add force vector [5,3] onto joint A..
        /// </summary>
        internal static string AddForce {
            get {
                return ResourceManager.GetString("AddForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start the joint-adding process. You will be prompted &quot;A:&quot;, &quot;B:&quot;  Press Enter to quit the flow. You can restart the process any time. Note that this process do not impact the truss directly. Any un-linked joints will be ignored..
        /// </summary>
        internal static string AddJoints {
            get {
                return ResourceManager.GetString("AddJoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program ASSUME the equilibrium of the truss, 
        ///and does not assume extreme cases (e.g. trusses not 
        ///in equilibrium. Please do not be surprised if the 
        ///program does not work as intended on some edgy 
        ///trusses..
        /// </summary>
        internal static string Assumption_Message {
            get {
                return ResourceManager.GetString("Assumption_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The flow of the program is outlined as follows:
        ///1. Add joints
        ///2. Link joints, or, Add forces onto a joint. 
        ///3. Repeat step 1. and 2.
        ///4. When feel ready, solve the truss and get the result.
        ///5. If the truss is of little use, restart..
        /// </summary>
        internal static string Flow_Message {
            get {
                return ResourceManager.GetString("Flow_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The help menu that you see right here..
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter &apos;help&apos; for a complete help menu ....
        /// </summary>
        internal static string Help_Welcome {
            get {
                return ResourceManager.GetString("Help_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link the joints. 
        ///    Syntax: &apos;link ab&apos;. This links joint A and joint B (case insensative)..
        /// </summary>
        internal static string LinkJoints {
            get {
                return ResourceManager.GetString("LinkJoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Look up the internal force of a specific edge. Should be called after solving.
        ///    Syntax: see ab cd de&apos;. This looks up the internal forces in member AB, CD and DE..
        /// </summary>
        internal static string Lookup {
            get {
                return ResourceManager.GetString("Lookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Look up the maximum internal force..
        /// </summary>
        internal static string MaxInternalForce {
            get {
                return ResourceManager.GetString("MaxInternalForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Look up the minimum intenral force..
        /// </summary>
        internal static string MinInternalForce {
            get {
                return ResourceManager.GetString("MinInternalForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prints all added forces..
        /// </summary>
        internal static string PrintForce {
            get {
                return ResourceManager.GetString("PrintForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prints all added joints..
        /// </summary>
        internal static string PrintJoints {
            get {
                return ResourceManager.GetString("PrintJoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prints all added members..
        /// </summary>
        internal static string PrintMembers {
            get {
                return ResourceManager.GetString("PrintMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quits the program..
        /// </summary>
        internal static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This solve for the truss and print out all solved internal forces..
        /// </summary>
        internal static string Render {
            get {
                return ResourceManager.GetString("Render", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resets the coordinate of a particular joint. 
        ///    Syntax: &apos;reset a 3 4&apos;. This resets joint A to coordinate (3,4)..
        /// </summary>
        internal static string ResetJointCoord {
            get {
                return ResourceManager.GetString("ResetJointCoord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart the truss-building process. Clear all progress..
        /// </summary>
        internal static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully restarted ....
        /// </summary>
        internal static string RestartMessage {
            get {
                return ResourceManager.GetString("RestartMessage", resourceCulture);
            }
        }
    }
}
